### PR TITLE
step-05: Explain how requests for socket.io.js are served

### PR DESCRIPTION
**Pull request by PierreFritsch**
Proposal to solve https://github.com/googlecodelabs/webrtc-web/issues/28

### CODE REVIEW

**Comment by nitobuendia** [comment]
@PierreFritsch I am having issues understanding why this is relevant and better; compared to other options like documenting a bit better on the codelab about node.js

Could you explain this further?

Thank you!

**Comment by PierreFritsch** [comment]
@nitobuendia I agree that it would be sufficient to add a quick explanation in the [codelab](https://codelabs.developers.google.com/codelabs/webrtc-web/#6) below the code for `index.html`.

imho a sentence like: 

> Requests to the file `/socket.io/socket.io.js` are intercepted and served by the Socket.io server.

would help newbies so that they won't start searching where this file is located in their file system.

**Comment by nitobuendia** [comment]
@PierreFritsch Thanks again for your response.

I was talking to @samdutton and we agree with your comment of adding a clarification.

However, we were wondering if something in more simple terms could be clearer to the user. For example:



What do you think? Your version might be more correct, but perhaps this makes it easy to understand for the user that they do not need to add the file, but run node instead.



Also, perhaps, it would be great to add it to every step where socket.io is used :)

**Comment by PierreFritsch** [comment]
(Did the copy-and-paste go wrong? I can't read your proposal...)

**Comment by nitobuendia** [comment]
It did! I think I might not have wrapped it in "code" and disappeared. Thanks for noticing :)

The proposed text was:
`<!-- This file is automatically added/served when running "node index.js". -->`

**Comment by PierreFritsch** [comment]
@nitobuendia it sounds good, I updated the PR.

**Comment by samdutton** [comment]
LGTM.

**Pull request merged**
