### PR TITLE
[fix]:node-static -> mime.lookup is not a function

### PR DESCRIPTION
**Pull request by GitScrum**
```node
/Users/superuser/Downloads/webrtc-web-master/step-04/node_modules/node-static/lib/node-static.js:348
                      mime.lookup(files[0]) ||
                           ^

TypeError: mime.lookup is not a function
    at Server.respond (/Users/superuser/Downloads/webrtc-web-master/step-04/node_modules/node-static/lib/node-static.js:348:28)
    at /Users/superuser/Downloads/webrtc-web-master/step-04/node_modules/node-static/lib/node-static.js:64:22
    at FSReqWrap.oncomplete (fs.js:154:5)
```

### CODE REVIEW

**Comment by wouterkroes** [comment]
Suggested fix works! :)

**Comment by nitobuendia** [comment]
Fixes #47

**Comment by nitobuendia** [comment]
@samdutton This is ready for LGTM and merging.

**Comment by samdutton** [comment]
LGTM — will merge (but aware of comments re ^X.Y.Z versions elsewhere).

**Pull request merged**
